// Gabarito comentado — Simulado ENEM 23/05/2026 (60 questões)
// Conteúdo estático: futuramente este arquivo pode ser removido.

export interface GabaritoQuestao {
  numero: number;
  area: string;
  topico: string;
  resposta: string;
  comentario: string;
}

export const SIMULADO_GABARITO_TITULO = "Simulado ENEM — 23/05/2026";
export const SIMULADO_GABARITO_TOTAL = 60;

// Apenas as letras do gabarito, na ordem das questões (índice 0 = questão 1)
export const SIMULADO_GABARITO_CHAVE: string[] = ["B","B","A","C","A","D","A","B","C","B","B","C","C","C","B","B","B","C","B","A","B","C","A","B","D","C","B","C","C","C","B","B","D","D","C","B","B","A","A","B","B","B","C","B","B","D","C","C","C","C","D","B","B","D","B","A","D","B","B","B"];

export const SIMULADO_GABARITO: GabaritoQuestao[] = [
  { numero: 1, area: "Linguagens, Códigos e suas Tecnologias", topico: "Comunicação e Poder nas Primeiras Civilizações", resposta: "B", comentario: "O Texto I é explícito ao afirmar que a escrita cuneiforme foi \"inicialmente empregada para registros administrativos e contábeis em tabuletas de argila\". Embora tenha posteriormente expandido suas funções (leis, tratados, narrativas míticas), sua gênese está vinculada ao controle burocrático-econômico das primeiras sociedades estatais mesopotâmicas, que demandavam registros sistemáticos de impostos, estoques de cereais, transações comerciais e distribuição de trabalho. A alternativa (a) é incorreta porque as narrativas religiosas foram função posterior; (c) erra ao sugerir democratização, quando o texto enfatiza restrição; (d) limita erroneamente a função inicial apenas à diplomacia; (e) também restringe indevidamente às funções tardias." },
  { numero: 2, area: "Linguagens, Códigos e suas Tecnologias", topico: "Comunicação e Poder nas Primeiras Civilizações", resposta: "B", comentario: "O texto estabelece claramente que os escribas \"detinham o monopólio do letramento e, consequentemente, exerciam influência política e econômica desproporcional em relação à sua representatividade demográfica\". Isso configura acumulação de capital simbólico (conceito bourdieusiano) — conhecimento especializado que se converte em poder político e econômico. A alternativa (a) é contraditória, pois houve concentração, não horizontalização; (c) inverte o processo real; (d) é factualmente incorreta, pois as hierarquias persistiram; (e) também contradiz o texto, que evidencia centralização administrativa via escribas." },
  { numero: 3, area: "Linguagens, Códigos e suas Tecnologias", topico: "Comunicação e Poder nas Primeiras Civilizações", resposta: "A", comentario: "A comparação entre as duas épocas fundamenta-se na tese de que o acesso à informação é condição necessária, mas não suficiente, para autonomia e participação plena. O Texto II afirma que \"letramento digital, curadoria algorítmica e bolhas informacionais configuram barreiras menos visíveis, porém igualmente excludentes\". Ou seja, mesmo com aparente democratização tecnológica, permanecem assimetrias que impedem o exercício substantivo da cidadania comunicativa. A alternativa (b) contradiz ambos os textos, que mostram persistência de hierarquias; (c) é excessivamente determinista; (d) desconsidera a crítica pós-colonial contemporânea; (e) nega as estruturas materiais de poder evidenciadas." },
  { numero: 4, area: "Linguagens, Códigos e suas Tecnologias", topico: "Comunicação e Poder nas Primeiras Civilizações", resposta: "C", comentario: "A locução \"menos visíveis\" estabelece relação comparativa que relativiza a evidência das barreiras contemporâneas em relação às antigas. No passado, a exclusão era óbvia (apenas escribas dominavam a escrita); hoje, as barreiras são mais sutis (algoritmos, bolhas), mas não menos eficazes. Trata-se de comparação que gradua a visibilidade fenomênica, não de antonímia absoluta (a), sinonímia (b), hipérbole (d) ou eufemismo (e)." },
  { numero: 5, area: "Linguagens, Códigos e suas Tecnologias", topico: "Comunicação e Poder nas Primeiras Civilizações", resposta: "A", comentario: "Na teoria de Bourdieu, o capital cultural opera como mecanismo de reprodução de estruturas de dominação simbólica. Escribas na Mesopotâmia e detentores de letramento digital hoje não apenas possuem conhecimento especializado, mas esse conhecimento legitima e naturaliza hierarquias sociais, convertendo-se em poder político-econômico. Não se trata de resistência contra-hegemônica (b), democratização (c), neutralização de desigualdades (d) ou superação dialética (e), mas de perpetuação de assimetrias através do monopólio de competências simbólicas valorizadas." },
  { numero: 6, area: "Linguagens, Códigos e suas Tecnologias", topico: "Comunicação e Poder nas Primeiras Civilizações", resposta: "D", comentario: "O excerto I (\"A escrita gradualmente expandiu-se para documentar leis, tratados...\") utiliza predominantemente função referencial ao descrever objetivamente processos históricos. O excerto II (\"curadoria algorítmica e bolhas informacionais configuram barreiras...\") também apresenta função referencial, mas articula função metalinguística ao discutir criticamente os próprios processos comunicacionais e suas limitações estruturais. Não há função emotiva (a) — ausência de juízos subjetivos explícitos; função conativa (b) seria apelo direto ao leitor; função fática (e) refere-se à manutenção do canal; função poética privilegia o arranjo formal da mensagem." },
  { numero: 7, area: "Linguagens, Códigos e suas Tecnologias", topico: "Comunicação e Poder nas Primeiras Civilizações", resposta: "A", comentario: "O Código de Hammurabi e algoritmos de recomendação compartilham função estrutural: normatização do comportamento coletivo através de regras codificadas cujo funcionamento é opaco aos sujeitos regulados. Hammurabi estabelecia normas jurídicas que a maioria não conseguia ler (escritas em cuneiforme); algoritmos contemporâneos regulam fluxos informacionais através de códigos proprietários inacessíveis aos usuários. Ambos exercem poder normativo mediante opacidade técnica. As demais alternativas estabelecem falsas equivalências: zigurates eram templos com dimensão simbólica central (b); agricultura mesopotâmica era hierárquica (c); politeísmo não implica descentralização política (d); cidades-estado eram hierarquizadas internamente (e)." },
  { numero: 8, area: "Linguagens, Códigos e suas Tecnologias", topico: "Cartografia e Representação do Espaço Geográfico", resposta: "B", comentario: "A geografia crítica interpreta a projeção de Mercator como reflexo e reforço de relações de poder geopolítico historicamente assimétricas. Criada no século XVI durante expansão colonial europeia, essa projeção amplia o hemisfério norte (Europa, América do Norte) e reduz regiões equatoriais e sul global, reproduzindo simbolicamente hierarquias coloniais. Não se trata de neutralidade técnica (a), pois toda representação envolve escolhas; não foi superada por tecnologias digitais (c), que ainda a utilizam amplamente; não houve estratégia deliberada de ocultação (d), mas consequência naturalizada de escolhas técnicas ideologicamente situadas; (e) ignora as implicações sociopolíticas das escolhas cartográficas." },
  { numero: 9, area: "Linguagens, Códigos e suas Tecnologias", topico: "Cartografia e Representação do Espaço Geográfico", resposta: "C", comentario: "Cálculo direto: África (30,37 milhões km²) / Groenlândia (2,16 milhões km²) = 14,06 ≈ 14:1. A projeção de Mercator inverte visualmente essa proporção, representando a Groenlândia com tamanho aparente similar à África, o que constitui distorção dramática que evidencia o caráter ideológico das representações cartográficas." },
  { numero: 10, area: "Linguagens, Códigos e suas Tecnologias", topico: "Cartografia e Representação do Espaço Geográfico", resposta: "B", comentario: "A projeção de Peters (1973) emerge no contexto de crítica pós-colonial e movimentos de descolonização africana e asiática. Ao preservar proporcionalidade de áreas, Peters questionava o eurocentrismo implícito na hegemonia de Mercator, valorizando a perspectiva do Sul global. Não se trata de positivismo (a), que busca neutralidade; a Guerra Fria (c) não é contexto primário; revolução técnico-científica (d) é muito ampla; declínio do Estado-nação (e) não caracteriza os anos 1970." },
  { numero: 11, area: "Linguagens, Códigos e suas Tecnologias", topico: "Cartografia e Representação do Espaço Geográfico", resposta: "B", comentario: "Escala 1:5.000.000 significa que 1 cm no mapa = 5.000.000 cm na realidade = 50 km. Para 350 km reais: 350 km ÷ 50 km/cm = 7,0 cm no mapa. Alternativamente: distância no mapa = distância real / denominador da escala = 35.000.000 cm / 5.000.000 = 7 cm." },
  { numero: 12, area: "Linguagens, Códigos e suas Tecnologias", topico: "Cartografia e Representação do Espaço Geográfico", resposta: "C", comentario: "Navegação marítima e aérea por rumo constante (loxodromia) exige preservação de ângulos, pois o navegador precisa manter direção constante em relação ao norte magnético. Essa propriedade denomina-se conformidade angular, característica central da projeção de Mercator, que por isso dominou a cartografia náutica desde o século XVI. Equidistância (a) não é possível em todas as direções simultaneamente; equivalência (b) distorceria ângulos; afilacidade (d) não é alcançável; ortogonalidade (e) não garante preservação angular." },
  { numero: 13, area: "Linguagens, Códigos e suas Tecnologias", topico: "Cartografia e Representação do Espaço Geográfico", resposta: "C", comentario: "Sob perspectiva semiótica, mapas são construções discursivas que selecionam, hierarquizam e interpretam elementos espaciais segundo intencionalidades específicas (políticas, econômicas, culturais). Não são espelhos neutros da realidade (a), pois toda representação envolve mediação; não são puramente icônicos (b), pois utilizam convenções simbólicas (cores, símbolos); não são exclusivamente quantitativos (d), pois carregam dimensões qualitativas e ideológicas; sua leitura depende de competências culturais (e), não sendo universais." },
  { numero: 14, area: "Linguagens, Códigos e suas Tecnologias", topico: "Funções da Linguagem e Publicidade Multilíngue", resposta: "C", comentario: "\"Seu futuro não espera. Construa hoje...\" emprega função conativa (ou apelativa) ao interpelar diretamente o destinatário mediante verbos no imperativo (\"construa\") e pronome possessivo de segunda pessoa (\"seu\"), visando persuasão comportamental (matricular-se, contratar serviços). Não é função referencial (a), que seria informativa-descritiva; não é emotiva (b), centrada no emissor; não é fática (d), que testaria o canal; não é metalinguística (e), que discutiria o próprio código." },
  { numero: 15, area: "Linguagens, Códigos e suas Tecnologias", topico: "Funções da Linguagem e Publicidade Multilíngue", resposta: "B", comentario: "A metáfora projeta o domínio concreto da arquitetura civil (construção de pontes físicas) sobre o domínio abstrato do planejamento estratégico (preparação para o futuro profissional). \"Construir pontes\" significa investir em educação/capacitação hoje que permitirá \"atravessar\" (alcançar objetivos) no futuro. Não é temporalidade abstrata (a) o destino primário; não é imobilidade social (c), mas mobilidade; não é isolamento (d), mas conexão; não é aleatoriedade (e), mas planejamento deliberado." },
  { numero: 16, area: "Linguagens, Códigos e suas Tecnologias", topico: "Funções da Linguagem e Publicidade Multilíngue", resposta: "B", comentario: "\"Your future won't wait\" emprega o modal will na forma negativa para expressar predição enfática que ressalta a urgência e inevitabilidade da progressão temporal. Não é pedido educado (a), pois não há estrutura condicional cortês; não é hábito passado (c), que demandaria \"used to\" ou \"would\"; não é possibilidade condicional (d), pois afirma categoricamente; não é obrigação imposta (e), que exigiria \"must\" ou \"have to\"." },
  { numero: 17, area: "Linguagens, Códigos e suas Tecnologias", topico: "Funções da Linguagem e Publicidade Multilíngue", resposta: "B", comentario: "A inserção de dados da PNAD/IBGE cumpre legitimação argumentativa através de evidências empíricas (dados quantitativos) e autoridade institucional (fonte governamental reconhecida). Confere credibilidade à campanha ao fundamentar afirmações em pesquisa científica. Não é mera ornamentação estética (a); não visa confundir (c), mas esclarecer; não desvia atenção (d), mas reforça argumentos; não é fim em si (e), mas meio retórico." },
  { numero: 18, area: "Linguagens, Códigos e suas Tecnologias", topico: "Funções da Linguagem e Publicidade Multilíngue", resposta: "C", comentario: "Margem de erro de ±2,3 pontos percentuais indica que o intervalo de confiança do parâmetro populacional varia ±2,3 pontos em relação ao estimador amostral. Se a amostra indicou 60% de aprovação, o valor populacional verdadeiro situa-se provavelmente entre 57,7% e 62,3% (com determinado nível de confiança, usualmente 95%). Não significa que 2,3% forneceram dados inconsistentes (a); não é 97,7% de confiabilidade (b), conceito distinto; não é viés sistemático (d); não se refere ao tamanho amostral (e)." },
  { numero: 19, area: "Linguagens, Códigos e suas Tecnologias", topico: "Funções da Linguagem e Publicidade Multilíngue", resposta: "B", comentario: "O letramento crítico — capacidade de identificar estratégias persuasivas, analisar fontes, reconhecer vieses — configura-se como competência cognitiva que possibilita posicionamento reflexivo e autonomia diante de discursos hegemônicos. Permite ao receptor não ser passivamente manipulado, mas avaliar criticamente mensagens. Não é irrelevante (a), mas fundamental em sociedades saturadas de informação; não é obstáculo ao consumo (c), mas mediação qualificada; não é exclusiva de especialistas (d), mas desejável para todos; não é resistência anacrônica (e), mas necessidade contemporânea." },
  { numero: 20, area: "Linguagens, Códigos e suas Tecnologias", topico: "Pensamento Filosófico Clássico e Democracia", resposta: "A", comentario: "Sócrates estabelece tensão entre obediência às leis convencionais da pólis (nomia) e obediência ao imperativo divino/racional (physis/natureza/razão). Esse conflito fundamenta o problema filosófico perene sobre a relação entre convenção (leis humanas, contingentes, mutáveis) e natureza (princípios racionais/divinos, universais, imutáveis). Não é fé vs. racionalidade (b), pois Sócrates integra ambas; não é apologia da democracia (c), pois Sócrates era crítico da democracia ateniense; não nega relevância da metafísica (d); não é impossibilidade de conciliação (e), mas tensão produtiva." },
  { numero: 21, area: "Linguagens, Códigos e suas Tecnologias", topico: "Pensamento Filosófico Clássico e Democracia", resposta: "B", comentario: "A metáfora do moscardo que importuna o cavalo estabelece a função crítico-reflexiva da filosofia: desestabilizar certezas consolidadas, questionar dogmas, estimular pensamento autônomo, incomodar a acomodação intelectual. O filósofo é agente de inquietação produtiva. Não é entretenimento elitista (a); não é atividade contemplativa apartada (c), pois Sócrates atuava no espaço público; não mantém status quo (d), mas o questiona; não é retórica agonística vazia (e), mas busca da verdade." },
  { numero: 22, area: "Linguagens, Códigos e suas Tecnologias", topico: "Pensamento Filosófico Clássico e Democracia", resposta: "C", comentario: "\"Uma vida sem exame não é digna de ser vivida\" articula-se com o conceito kantiano de Maioridade (Aufklärung) — emancipação intelectual através do uso autônomo da razão, saída da menoridade autoimposta. Ambos — Sócrates e Kant — enfatizam autonomia crítica contra heteronomia acrítica. Não é imperativo hipotético (a), que é condicional; não são juízos sintéticos a posteriori (b), conceito epistemológico distinto; não é sublime matemático (d), categoria estética; não são antinomias (e), contradições metafísicas." },
  { numero: 23, area: "Linguagens, Códigos e suas Tecnologias", topico: "Pensamento Filosófico Clássico e Democracia", resposta: "A", comentario: "A ironia reside na contradição entre a afirmação explícita \"Nossa democracia está em crise!\" e a postura de consultar acriticamente \"trending topics\" para formar opinião — ou seja, delegar o pensamento crítico aos algoritmos, precisamente o comportamento que enfraquece a democracia. Não é tecnologia vs. tradição (b); não é coletivo vs. individual (c), pois trending topics criam ilusão de coletividade; não é linguagem vs. gravidade (d); não é consulta a smartphones vs. fontes primárias (e), mas o modo acrítico dessa consulta." },
  { numero: 24, area: "Linguagens, Códigos e suas Tecnologias", topico: "Pensamento Filosófico Clássico e Democracia", resposta: "B", comentario: "Ambos os textos problematizam a tensão entre pensamento crítico autônomo (exame socrático, reflexão independente) e adesão acrítica a opiniões hegemônicas (condenação de Sócrates pela maioria democrática; formação de opinião por trending topics algorítmicos). Não afirmam inevitabilidade de declínio (a); não comparam tipos de democracia (c); não são incompatíveis (d), mas dialogam produtivamente; não negam relevância da educação filosófica (e), mas a afirmam." },
  { numero: 25, area: "Linguagens, Códigos e suas Tecnologias", topico: "Pensamento Filosófico Clássico e Democracia", resposta: "D", comentario: "Formação de opinião mediada por trending topics relaciona-se com o conceito durkheimiano de consciência coletiva — conjunto de crenças e sentimentos comuns que exercem coerção sobre indivíduos. Os trending topics constituem manifestação contemporânea desse fenômeno: opiniões coletivas que pressionam adesão individual. Não é solidariedade mecânica (a), típica de sociedades simples; anomia (b) seria ausência de normas; fato social (c) é conceito mais amplo; divisão do trabalho (e) refere-se à especialização funcional." },
  { numero: 26, area: "Linguagens, Códigos e suas Tecnologias", topico: "Manifestações Artístico-Culturais e Identidade", resposta: "C", comentario: "A caracterização das pinturas rupestres como transcendentes da \"mera documentação utilitária\" indica que cumprem função simbólico-ritual: elaboração de sentidos existenciais, cosmológicos e estéticos. Não são exclusivamente registro pragmático de técnicas (a); não são primordialmente decorativas (b); não são demarcação econômica (d); não são entretenimento lúdico vazio (e). Representam sistemas complexos de significação que articulam dimensões práticas, ritualísticas e artísticas." },
  { numero: 27, area: "Linguagens, Códigos e suas Tecnologias", topico: "Manifestações Artístico-Culturais e Identidade", resposta: "B", comentario: "O paralelismo entre suportes materiais distintos (\"paredes de pedra\"/\"telas de cristal líquido\") articula reflexão sobre continuidade antropológica: a necessidade humana de produzir significados simbólicos persiste através de diferentes épocas e tecnologias. Não afirma superação evolutiva (a); não declara eliminação da comunicação não-verbal (c); não nega funções rituais contemporâneas (d); não são incomensuráveis (e), mas conectados pela permanência da função simbólica." },
  { numero: 28, area: "Linguagens, Códigos e suas Tecnologias", topico: "Manifestações Artístico-Culturais e Identidade", resposta: "C", comentario: "A pergunta \"Who are we, who translate ancient symbols while creating new codes...?\" expressa reflexão sobre a condição humana como simultaneamente herdeira de tradições simbólicas e produtora de novos sistemas semióticos. Não afirma superioridade contemporânea (a); não nega diálogo entre épocas (b); não critica foco exclusivo em inovação (d), mas reconhece continuidade; não declara ruptura completa (e), mas conexão através da função simbólica." },
  { numero: 29, area: "Linguagens, Códigos e suas Tecnologias", topico: "Manifestações Artístico-Culturais e Identidade", resposta: "C", comentario: "A valorização de patrimônios arqueológicos relaciona-se com construção de identidades coletivas através da memória social e reconhecimento de pluralidade cultural. Patrimônios funcionam como âncoras identitárias que conectam passado, presente e futuro, legitimando diversidade. Não é apenas mercantilização (a); não é homogeneização (b), mas preservação de diversidade; não é hierarquização evolutiva eurocêntrica (d); não é folclorização essencialista (e), quando patrimônio é vivo e ressignificado." },
  { numero: 30, area: "Linguagens, Códigos e suas Tecnologias", topico: "Manifestações Artístico-Culturais e Identidade", resposta: "C", comentario: "A técnica das pinturas rupestres exemplifica dialética entre recursos materiais disponíveis (pigmentos minerais, superfícies rochosas) e intencionalidades estético-comunicativas dos produtores. Não há autonomia absoluta do simbólico (a); não há determinismo tecnológico rígido (b); não são irrelevantes os suportes (d); não há superioridade intrínseca de materiais contemporâneos (e). Materialidade e simbolismo interagem dinamicamente." },
  { numero: 31, area: "Ciências Exatas e da Natureza", topico: "Propriedades da Matéria e Mudanças de Estado", resposta: "B", comentario: "A densidade anômala da água explica-se pela estrutura cristalina hexagonal do gelo, que organiza moléculas com espaçamento intermolecular maior que no estado líquido, resultando em menor densidade. No gelo, ligações de hidrogênio estabilizam arranjo tridimensional rígido e \"aberto\"; na água líquida, moléculas aproximam-se mais. Não há rompimento completo de ligações H (a); o aumento de volume ocorre no congelamento abaixo de 0°C, não abaixo de 4°C (c); há interações intermoleculares no líquido (d); não se formam novas ligações covalentes no gelo (e)." },
  { numero: 32, area: "Ciências Exatas e da Natureza", topico: "Propriedades da Matéria e Mudanças de Estado", resposta: "B", comentario: "Durante mudanças de estado (fusão, ebulição), a temperatura permanece constante porque toda energia térmica fornecida é utilizada para vencer forças intermoleculares (romper ligações de hidrogênio), sem alterar a energia cinética média das partículas (que determina a temperatura). Não há aumento simultâneo de temperatura e rompimento de ligações (a); a pressão não varia significativamente (c); moléculas não perdem energia cinética (d); não há transformação química (e)." },
  { numero: 33, area: "Ciências Exatas e da Natureza", topico: "Propriedades da Matéria e Mudanças de Estado", resposta: "D", comentario: "Calor sensível: Q = m × c × ΔT = 100 g × 2,1 J/(g·°C) × [0°C - (-20°C)] = 100 × 2,1 × 20 = 4.200 J. Importante notar que ΔT = 20°C (variação de -20°C para 0°C)." },
  { numero: 34, area: "Ciências Exatas e da Natureza", topico: "Propriedades da Matéria e Mudanças de Estado", resposta: "D", comentario: "Calor latente de fusão: Q = m × L = 100 g × 334 J/g = 33.400 J. Durante a fusão, toda essa energia rompe ligações intermoleculares sem alterar temperatura." },
  { numero: 35, area: "Ciências Exatas e da Natureza", topico: "Propriedades da Matéria e Mudanças de Estado", resposta: "C", comentario: "Velocidade média: v = Δs / Δt = 150 m / 30 s = 5,0 m/s. Em MRU, velocidade é constante." },
  { numero: 36, area: "Ciências Exatas e da Natureza", topico: "Propriedades da Matéria e Mudanças de Estado", resposta: "B", comentario: "A relevância ecológica da densidade anômala consiste em que a camada de gelo superficial atua como isolante térmico, preservando água líquida abaixo (onde peixes e organismos aquáticos sobrevivem). Se gelo fosse mais denso, afundaria, e corpos d'água congelariam de baixo para cima, eliminando vida aquática (a é falsa por isso); água líquida não evapora mais rapidamente por ser mais densa (c); gelo não sedimenta (d); anomalia possibilita formação de gelo (e está incorreta)." },
  { numero: 37, area: "Ciências Exatas e da Natureza", topico: "Cinemática e Mobilidade Urbana", resposta: "B", comentario: "Em MRU, a velocidade escalar permanece constante, indicando que a aceleração é nula (a = 0). Não aumenta linearmente (a), isso seria MRUV; não varia inversamente à distância (c); não depende da massa para movimento horizontal sem atrito (d); não é nula (e)." },
  { numero: 38, area: "Ciências Exatas e da Natureza", topico: "Cinemática e Mobilidade Urbana", resposta: "A", comentario: "Velocidade média: v = Δs / Δt = 15 km / (103/60) h = 15 km / 1,717 h ≈ 8,7 km/h. O tempo de 1h43min = 103 min = 1,717 h. Este valor é significativamente inferior aos 20 km/h mencionados como velocidade média modal do automóvel, evidenciando impacto de congestionamentos." },
  { numero: 39, area: "Ciências Exatas e da Natureza", topico: "Cinemática e Mobilidade Urbana", resposta: "A", comentario: "A diferença entre velocidade instantânea e média evidencia que a velocidade instantânea é geralmente superior à velocidade média em trajetos com congestionamentos, pois em vias expressas atinge-se 80-100 km/h momentaneamente, mas paradas reduzem drasticamente a média. Não são necessariamente iguais (b); velocidade instantânea é relevante (c); velocidade média depende das variações instantâneas (d); velocidades instantâneas elevadas não garantem média elevada se houver muitas paradas (e)." },
  { numero: 40, area: "Ciências Exatas e da Natureza", topico: "Cinemática e Mobilidade Urbana", resposta: "B", comentario: "Tempo: t = Δs / v = 8 km / 16 km/h = 0,5 h = 30 minutos." },
  { numero: 41, area: "Ciências Exatas e da Natureza", topico: "Cinemática e Mobilidade Urbana", resposta: "B", comentario: "A superioridade do metrô relaciona-se com segregação de vias (trilhos exclusivos) que elimina interferências de tráfego misto, semáforos, pedestres, congestionamentos. Não é apenas características mecânicas (a); não é capacidade de carga (c), conceito irrelevante para velocidade média; não há proibição de automóveis (d); a demanda por transporte individual persiste (e)." },
  { numero: 42, area: "Ciências Exatas e da Natureza", topico: "Cinemática e Mobilidade Urbana", resposta: "B", comentario: "Razão: 35:20 = (35÷5):(20÷5) = 7:4. Simplificação pelo MDC(35, 20) = 5." },
  { numero: 43, area: "Ciências Exatas e da Natureza", topico: "Biodiversidade e Sistemática Biológica", resposta: "C", comentario: "A sistemática filogenética fundamenta-se no princípio de que grupos que compartilham maior número de sinapomorfias (caracteres derivados exclusivos compartilhados) descendem de ancestral comum mais recente. No cladograma, Archaea e Bacteria formam clado porque compartilham características derivadas que os distinguem dos eucariotos. Caracteres análogos (a) indicam convergência, não parentesco; semelhança morfológica (b) pode ser superficial; ordem alfabética (d) é irrelevante; ambientes similares (e) não indicam parentesco filogenético." },
  { numero: 44, area: "Ciências Exatas e da Natureza", topico: "Biodiversidade e Sistemática Biológica", resposta: "B", comentario: "O alto endemismo da Mata Atlântica explica-se por fragmentação histórica e diversidade de microclimas, que promovem especiação alopátrica (isolamento geográfico favorecendo diferenciação) e reduzem dispersão entre populações isoladas. Não é homogeneidade (a), mas heterogeneidade; não é ausência de pressões seletivas (c); não é superioridade adaptativa intrínseca (d); não é impossibilidade de migração total (e), mas redução." },
  { numero: 45, area: "Ciências Exatas e da Natureza", topico: "Biodiversidade e Sistemática Biológica", resposta: "B", comentario: "No sistema binomial, Panthera é o gênero (compartilhado com leões, tigres, leopardos) e onca o epíteto específico distintivo da onça-pintada sul-americana. A alternativa (a) inverte os termos; (c) confunde com categoria taxonômica superior (família seria Felidae); (d) é interpretação fantasiosa; (e) também é incorreta." },
  { numero: 46, area: "Ciências Exatas e da Natureza", topico: "Biodiversidade e Sistemática Biológica", resposta: "D", comentario: "Espécies endêmicas: 12.000 × 0,44 = 5.280 espécies. Cálculo direto de 44% de 12.000." },
  { numero: 47, area: "Ciências Exatas e da Natureza", topico: "Biodiversidade e Sistemática Biológica", resposta: "C", comentario: "Dados moleculares oferecem vantagem porque semelhanças genéticas refletem mais diretamente descendência comum, reduzindo confusão entre homologia (ancestralidade comum) e analogia (convergência evolutiva). Não há relógio molecular perfeito (a), pois taxas mutacionais variam; caracteres moleculares não são imunes a seleção (b); DNA não está em vírus acelulares (d), que têm RNA ou DNA, mas não são vivos por definição tradicional; análises moleculares complementam, não eliminam estudos morfológicos (e)." },
  { numero: 48, area: "Ciências Exatas e da Natureza", topico: "Biodiversidade e Sistemática Biológica", resposta: "C", comentario: "A ampla distribuição da onça-pintada relaciona-se com plasticidade ecológica — capacidade de habitar múltiplos biomas (florestas amazônicas, Mata Atlântica, Cerrado, Pantanal, até áreas semiáridas). Não há homogeneidade climática continental (a); há barreiras geográficas, mas a espécie as atravessou historicamente (b); não foi introdução antrópica recente (d); há competição com outros predadores (e), mas a onça-pintada é predador de topo dominante." },
  { numero: 49, area: "Ciências Exatas e da Natureza", topico: "Proporcionalidade e Aplicações Matemáticas", resposta: "C", comentario: "Proporção: 6 porções → 3 xícaras; 15 porções → x xícaras. Regra de três: x = (15 × 3) / 6 = 7,5 xícaras. Fator de multiplicação: 15/6 = 2,5; 3 × 2,5 = 7,5." },
  { numero: 50, area: "Ciências Exatas e da Natureza", topico: "Proporcionalidade e Aplicações Matemáticas", resposta: "C", comentario: "Proporção: 6 porções → 200 ml; 15 porções → x ml. x = (15 × 200) / 6 = 500 ml. Fator 2,5: 200 × 2,5 = 500 ml." },
  { numero: 51, area: "Ciências Exatas e da Natureza", topico: "Proporcionalidade e Aplicações Matemáticas", resposta: "D", comentario: "Escala 1:250.000 → 1 cm = 250.000 cm = 2,5 km. Para 75 km: 75 / 2,5 = 30 cm. Alternativamente: 75 km = 7.500.000 cm; 7.500.000 / 250.000 = 30 cm." },
  { numero: 52, area: "Ciências Exatas e da Natureza", topico: "Proporcionalidade e Aplicações Matemáticas", resposta: "B", comentario: "Velocidade inversamente proporcional ao tempo: se velocidade dobra, tempo reduz à metade. 20 minutos / 2 = 10 minutos." },
  { numero: 53, area: "Ciências Exatas e da Natureza", topico: "Proporcionalidade e Aplicações Matemáticas", resposta: "B", comentario: "Razão açúcar:chocolate = 2 xícaras : 1 xícara = 2:1 (forma simplificada)." },
  { numero: 54, area: "Ciências Exatas e da Natureza", topico: "Proporcionalidade e Aplicações Matemáticas", resposta: "D", comentario: "Concentração: C = massa soluto / volume solvente = 50 g / 200 ml = 0,25 g/ml. Cálculo direto: 50/200 = 0,25." },
  { numero: 55, area: "Ciências Exatas e da Natureza", topico: "Energia, Sustentabilidade e Matrizes Energéticas", resposta: "B", comentario: "A predominância hidrelétrica relaciona-se com abundância de recursos hídricos (maior reserva hídrica renovável do mundo) e relevo propício (planaltos, quedas d'água) para construção de barragens, especialmente em bacias como Paraná, São Francisco, Tocantins-Araguaia. Não há ausência de outras fontes (a); há impactos socioambientais significativos (c) — deslocamento de populações, alteração de ecossistemas; não há superioridade absoluta (d); há viabilidade técnica de eólica/solar (e)." },
  { numero: 56, area: "Ciências Exatas e da Natureza", topico: "Energia, Sustentabilidade e Matrizes Energéticas", resposta: "A", comentario: "Energia define-se como capacidade de realizar trabalho ou transferir calor, mensurável em joules (J) no Sistema Internacional. Não é quantidade de matéria (b), isso é massa; não é velocidade (c); não é temperatura (d), embora relacionada; não é massa específica (e)." },
  { numero: 57, area: "Ciências Exatas e da Natureza", topico: "Energia, Sustentabilidade e Matrizes Energéticas", resposta: "D", comentario: "Energia útil: E_útil = eficiência × E_total = 0,25 × 34 MJ = 8,5 MJ. 75% (1 - 0,25) dissipam-se como calor." },
  { numero: 58, area: "Ciências Exatas e da Natureza", topico: "Energia, Sustentabilidade e Matrizes Energéticas", resposta: "B", comentario: "Para produzir 8,5 MJ úteis com eficiência de 90%: E_total = E_útil / eficiência = 8,5 MJ / 0,90 ≈ 9,4 MJ. O motor elétrico requer menos energia total para mesmo trabalho útil devido à maior eficiência." },
  { numero: 59, area: "Ciências Exatas e da Natureza", topico: "Energia, Sustentabilidade e Matrizes Energéticas", resposta: "B", comentario: "Etanol é renovável porque o carbono liberado na queima foi previamente capturado da atmosfera pela fotossíntese da cana-de-açúcar, fechando ciclo de curto prazo (diferente de combustíveis fósseis, que liberam carbono sequestrado há milhões de anos). A fermentação libera CO₂ (a é falsa); combustíveis vegetais têm densidade energética inferior (c é falsa); cana requer insumos químicos (d é falsa); biocombustíveis reduzem, não eliminam emissões (e é falsa)." },
  { numero: 60, area: "Ciências Exatas e da Natureza", topico: "Energia, Sustentabilidade e Matrizes Energéticas", resposta: "B", comentario: "A discrepância sugere que os 73% referem-se exclusivamente à geração elétrica, enquanto a matriz energética total (que inclui transportes rodoviários movidos a combustíveis fósseis, processos industriais, etc.) apresenta menor participação renovável. O gráfico específico é de geração elétrica, setor onde renováveis dominam no Brasil; a matriz energética total é mais diversificada. Não houve erro matemático (a); biomassa está incluída (c); nuclear é marginal no Brasil (d); fósseis persistem na matriz (e)." },
];
