/**
 * Taxonomia curada de micro-tópicos por matéria (base: Matriz de Referência do ENEM
 * e conteúdos programáticos usuais). É a lista fechada que a IA usa como candidatas ao
 * classificar cada questão — garante rótulos limpos e consistentes para o filtro do
 * simulado (modo "Treino Específico" → micro_topic_id).
 *
 * As chaves são exatamente os nomes de `subjects.name` no banco.
 */

export const MICRO_TOPICS_BY_SUBJECT: Record<string, string[]> = {
  Matemática: [
    'Funções',
    'Geometria Plana',
    'Geometria Espacial',
    'Geometria Analítica',
    'Trigonometria',
    'Probabilidade',
    'Estatística',
    'Análise Combinatória',
    'Progressões (PA e PG)',
    'Matemática Financeira',
    'Porcentagem',
    'Razão e Proporção',
    'Equações e Inequações',
    'Conjuntos Numéricos',
    'Grandezas e Medidas',
    'Matrizes e Sistemas Lineares',
  ],
  Física: [
    'Cinemática',
    'Dinâmica',
    'Estática e Hidrostática',
    'Trabalho e Energia',
    'Termologia e Termodinâmica',
    'Óptica',
    'Ondulatória',
    'Eletrodinâmica',
    'Eletromagnetismo',
    'Física Moderna',
    'Gravitação',
  ],
  Química: [
    'Atomística',
    'Tabela Periódica',
    'Ligações Químicas',
    'Funções Inorgânicas',
    'Reações Químicas',
    'Estequiometria',
    'Soluções',
    'Termoquímica',
    'Cinética Química',
    'Equilíbrio Químico',
    'Eletroquímica',
    'Química Orgânica',
    'Radioatividade',
  ],
  Biologia: [
    'Citologia',
    'Genética',
    'Evolução',
    'Ecologia',
    'Fisiologia Humana',
    'Botânica',
    'Zoologia',
    'Microbiologia e Doenças',
    'Bioquímica',
    'Biotecnologia',
    'Origem da Vida',
  ],
  História: [
    'Brasil Colônia',
    'Brasil Império',
    'Brasil República',
    'Era Vargas',
    'Ditadura Militar',
    'Idade Antiga',
    'Idade Média',
    'Idade Moderna',
    'Revolução Industrial',
    'Revoluções Burguesas',
    'Guerras Mundiais',
    'Guerra Fria',
    'Mundo Contemporâneo',
  ],
  Geografia: [
    'Climatologia',
    'Geomorfologia e Relevo',
    'Hidrografia',
    'Geografia Agrária',
    'Geografia Urbana',
    'Geografia da População',
    'Industrialização',
    'Globalização',
    'Geopolítica',
    'Questões Ambientais',
    'Cartografia',
    'Geografia do Brasil',
  ],
  Filosofia: [
    'Filosofia Antiga',
    'Filosofia Medieval',
    'Filosofia Moderna',
    'Filosofia Contemporânea',
    'Ética',
    'Filosofia Política',
    'Teoria do Conhecimento',
    'Estética',
    'Lógica',
  ],
  Sociologia: [
    'Teóricos Clássicos (Durkheim, Weber, Marx)',
    'Cultura e Sociedade',
    'Trabalho e Sociedade',
    'Movimentos Sociais',
    'Cidadania e Direitos',
    'Estado e Poder',
    'Desigualdade Social',
    'Indústria Cultural',
    'Globalização e Sociedade',
  ],
  Português: [
    'Interpretação de Texto',
    'Morfologia',
    'Sintaxe',
    'Semântica',
    'Variação Linguística',
    'Figuras de Linguagem',
    'Funções da Linguagem',
    'Coesão e Coerência',
    'Gêneros Textuais',
    'Fonética e Ortografia',
  ],
  Literatura: [
    'Trovadorismo e Humanismo',
    'Quinhentismo',
    'Barroco',
    'Arcadismo',
    'Romantismo',
    'Realismo e Naturalismo',
    'Parnasianismo e Simbolismo',
    'Modernismo',
    'Literatura Contemporânea',
    'Gêneros e Teoria Literária',
  ],
  Arte: [
    'Artes Visuais',
    'Música',
    'Teatro',
    'Dança',
    'Movimentos Artísticos',
    'História da Arte',
    'Arte Contemporânea',
  ],
  'Educação Física': [
    'Esportes',
    'Saúde e Qualidade de Vida',
    'Ginástica',
    'Jogos e Brincadeiras',
    'Corpo e Movimento',
    'História da Educação Física',
  ],
  Inglês: ['Interpretação de Texto', 'Vocabulário', 'Gramática'],
  Espanhol: ['Interpretação de Texto', 'Vocabulário', 'Gramática'],
};
