-- ADD INCOME AND FAMILY FIELDS TO PROFILES FOR SECRETARY CONTROL
-- Compromisso 360 | Migration 20260524020000

ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS family_members JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS family_income NUMERIC(10,2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS family_size INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS income_per_capita NUMERIC(10,2) DEFAULT 0.00;
